### ISSUE TITLE
no low power while sending or joining on LoRaWAN

### ISSUE THREAD

**Issue by nestorayuso** [disk91/stm32-it-sdk#18]
On joining or sending data in synchronous mode, the MCU is not stopped/slept while waiting for the send or join procedure to complete.

Function lorawan_driver_waitUntilEndOfExecution() is an active loop.
https://github.com/disk91/stm32-it-sdk/blob/1cc19a03f84bbcaaa9b4c02d719edf2aa7830e58/Src/drivers/lorawan/core/lorawan.c#L113-L119

**Comment by disk91** [comment]
The lorawan_driver_waitUntilEndOfExecution() is only used for the LoRa sync API. ex : itsdk_lorawan_join_sync()

If you choose the async API ex: itsdk_lorawan_join_async() this loop is not use and the async callback are use instead. That way the device is going to deep sleep over the main loop.

The  lorawan_driver_waitUntilEndOfExecution() function is __weak to be override if you want it to go deep sleep. The reason it is not doing this is deep sleep is because it is a bit complex to manage a correct wake-up outside of the main loop in a generic SDK and the wake-up condition can be multiple with required processing. By using a __weak function you can manage this the way you need in your firmware. 

That said, for the purpose you mention, the use of the async API answer your question with no extra specific development.
